# Generated by Django 3.0.5 on 2020-10-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='url',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
