# Generated by Django 3.0.5 on 2020-10-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0002_imagemodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
